### ISSUE TITLE
Add Brian Curcio, github: curcio, role: Judge of Argentina, auth: cruz

### ISSUE THREAD

**Issue by wmacevoy** [icpc/start-here#3]
Hi again, Warren

I'm trying to add Brian Curcio, judge of argentina, github: curcio, but I'm not able to do it because he is not member of the organization.

Could you help me with this?

Thanks!
Cristian  Cristian Ruz <cristian.ruz@gmail.com>

**Comment by wmacevoy** [comment]
request sent.

**Comment by cruz** [comment]
Thanks Warren, I'll continue here

**Comment by cruz** [comment]
Thanks. I'd like to invite another setter: pablobce

**Comment by wmacevoy** [comment]
Can you create a new issue? It will help keep track of this...
