### ISSUE TITLE
Add John P. Bonomo <bonomojp@westminster.edu>

### ISSUE THREAD

**Issue by wmacevoy** [icpc/start-here#4]
Hi Warren,

I'm the head judge from for ECNA and I would like to obtain one of the repositories you have set aside.  My login to git is

bonomojp@westminster.edu

Is there anything else you need from me?  Regardless, thanks for setting these repositories up.

John Bonomo
Head Judge
East Central North America Region

**Comment by wmacevoy** [comment]
Evidence: http://acm-ecna.ysu.edu/PastResults/2016/problemset.html

**Comment by wmacevoy** [comment]
Created na-east-central repository & team, invited John.

**Comment by bonomojp** [comment]
Thanks for setting this up, Warren.  I've added a bunch of stuff to the repository and would like to give my other judges access to it.  Do I do this by making them collaborators?  A assume they need a github account before they can join?

**Comment by wmacevoy** [comment]
Ok I set you as a maintainer of the na-east-central team, you should be able to invite members now (you can invite to an email or choose an existing github account).

**Comment by bonomojp** [comment]
Thanks!

John

Sent from my iPad

On Jul 18, 2018, at 7:18 PM, Warren MacEvoy <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I set you as a maintainer of the na-east-central team, you should be able to invite members now (you can invite to an email or choose an existing github account).
